/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.docs.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Services service. Represents a row in the &quot;AA_Services&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.docs.model.impl.ServicesModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.docs.model.impl.ServicesImpl}.
 * </p>
 *
 * @author ADMIN
 * @see Services
 * @see com.liferay.docs.model.impl.ServicesImpl
 * @see com.liferay.docs.model.impl.ServicesModelImpl
 * @generated
 */
public interface ServicesModel extends BaseModel<Services>, StagedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a services model instance should use the {@link Services} interface instead.
	 */

	/**
	 * Returns the primary key of this services.
	 *
	 * @return the primary key of this services
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this services.
	 *
	 * @param primaryKey the primary key of this services
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this services.
	 *
	 * @return the uuid of this services
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this services.
	 *
	 * @param uuid the uuid of this services
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the service ID of this services.
	 *
	 * @return the service ID of this services
	 */
	public long getServiceId();

	/**
	 * Sets the service ID of this services.
	 *
	 * @param serviceId the service ID of this services
	 */
	public void setServiceId(long serviceId);

	/**
	 * Returns the name of this services.
	 *
	 * @return the name of this services
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this services.
	 *
	 * @param name the name of this services
	 */
	public void setName(String name);

	/**
	 * Returns the description of this services.
	 *
	 * @return the description of this services
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this services.
	 *
	 * @param description the description of this services
	 */
	public void setDescription(String description);

	/**
	 * Returns the price of this services.
	 *
	 * @return the price of this services
	 */
	@AutoEscape
	public String getPrice();

	/**
	 * Sets the price of this services.
	 *
	 * @param price the price of this services
	 */
	public void setPrice(String price);

	/**
	 * Returns the company ID of this services.
	 *
	 * @return the company ID of this services
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this services.
	 *
	 * @param companyId the company ID of this services
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this services.
	 *
	 * @return the group ID of this services
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this services.
	 *
	 * @param groupId the group ID of this services
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this services.
	 *
	 * @return the user ID of this services
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this services.
	 *
	 * @param userId the user ID of this services
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this services.
	 *
	 * @return the user uuid of this services
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this services.
	 *
	 * @param userUuid the user uuid of this services
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this services.
	 *
	 * @return the create date of this services
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this services.
	 *
	 * @param createDate the create date of this services
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this services.
	 *
	 * @return the modified date of this services
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this services.
	 *
	 * @param modifiedDate the modified date of this services
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.liferay.docs.model.Services services);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.liferay.docs.model.Services> toCacheModel();

	@Override
	public com.liferay.docs.model.Services toEscapedModel();

	@Override
	public com.liferay.docs.model.Services toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}